
const preguntas = [
  ["¿Cómo se dice 'gato' en inglés?", "cat"],
  ["¿Cómo se dice 'perro' en inglés?", "dog"],
  ["¿Cómo se dice 'casa' en inglés?", "house"],
  ["¿Cómo se dice 'árbol' en inglés?", "tree"],
  ["¿Cómo se dice 'libro' en inglés?", "book"],
  ["¿Cómo se dice 'coche' en inglés?", "car"],
  ["¿Cómo se dice 'agua' en inglés?", "water"],
  ["¿Cómo se dice 'sol' en inglés?", "sun"],
  ["¿Cómo se dice 'luna' en inglés?", "moon"],
  ["¿Cómo se dice 'pan' en inglés?", "bread"],
  ["¿Cómo se dice 'ventana' en inglés?", "window"],
  ["¿Cómo se dice 'puerta' en inglés?", "door"],
  ["¿Cómo se dice 'mesa' en inglés?", "table"],
  ["¿Cómo se dice 'silla' en inglés?", "chair"],
  ["¿Cómo se dice 'niño' en inglés?", "boy"],
  ["¿Cómo se dice 'niña' en inglés?", "girl"],
  ["¿Cómo se dice 'amigo' en inglés?", "friend"],
  ["¿Cómo se dice 'escuela' en inglés?", "school"],
  ["¿Cómo se dice 'profesor' en inglés?", "teacher"],
  ["¿Cómo se dice 'ciudad' en inglés?", "city"],
  ["¿Cómo se dice 'perro grande' en inglés?", "big dog"],
  ["¿Cómo se dice 'gato pequeño' en inglés?", "small cat"],
  ["¿Cómo se dice 'familia' en inglés?", "family"],
  ["¿Cómo se dice 'comida' en inglés?", "food"],
  ["¿Cómo se dice 'bebida' en inglés?", "drink"],
  ["¿Cómo se dice 'cielo' en inglés?", "sky"],
["¿Cómo se dice 'mar' en inglés?", "sea"],
["¿Cómo se dice 'montaña' en inglés?", "mountain"],
["¿Cómo se dice 'río' en inglés?", "river"],
["¿Cómo se dice 'bosque' en inglés?", "forest"],
["¿Cómo se dice 'flor' en inglés?", "flower"],
["¿Cómo se dice 'fruta' en inglés?", "fruit"],
["¿Cómo se dice 'verdura' en inglés?", "vegetable"],
["¿Cómo se dice 'perro pequeño' en inglés?", "small dog"],
["¿Cómo se dice 'gato grande' en inglés?", "big cat"],
["¿Cómo se dice 'nube' en inglés?", "cloud"],
["¿Cómo se dice 'lluvia' en inglés?", "rain"],
["¿Cómo se dice 'viento' en inglés?", "wind"],
["¿Cómo se dice 'nieve' en inglés?", "snow"],
["¿Cómo se dice 'fuego' en inglés?", "fire"],
["¿Cómo se dice 'ratón' en inglés?", "mouse"],
["¿Cómo se dice 'pájaro' en inglés?", "bird"],
["¿Cómo se dice 'pez' en inglés?", "fish"],
["¿Cómo se dice 'caballo' en inglés?", "horse"],
["¿Cómo se dice 'vaca' en inglés?", "cow"],
["¿Cómo se dice 'cerdo' en inglés?", "pig"],
["¿Cómo se dice 'oveja' en inglés?", "sheep"],
["¿Cómo se dice 'pollo' en inglés?", "chicken"],
["¿Cómo se dice 'abeja' en inglés?", "bee"],
["¿Cómo se dice 'mariposa' en inglés?", "butterfly"],
["¿Cómo se dice 'tigre' en inglés?", "tiger"],
["¿Cómo se dice 'león' en inglés?", "lion"],
["¿Cómo se dice 'elefante' en inglés?", "elephant"],
["¿Cómo se dice 'jirafa' en inglés?", "giraffe"],
["¿Cómo se dice 'mono' en inglés?", "monkey"],
["¿Cómo se dice 'serpiente' en inglés?", "snake"],
["¿Cómo se dice 'cangrejo' en inglés?", "crab"],
["¿Cómo se dice 'delfín' en inglés?", "dolphin"],
["¿Cómo se dice 'ballena' en inglés?", "whale"],
["¿Cómo se dice 'oso' en inglés?", "bear"],
["¿Cómo se dice 'puente' en inglés?", "bridge"],
["¿Cómo se dice 'camino' en inglés?", "road"],
["¿Cómo se dice 'calle' en inglés?", "street"],
["¿Cómo se dice 'parque' en inglés?", "park"],
["¿Cómo se dice 'jardín' en inglés?", "garden"],
["¿Cómo se dice 'ciudad' en inglés?", "city"],
["¿Cómo se dice 'país' en inglés?", "country"],
["¿Cómo se dice 'montaña' en inglés?", "mountain"],
["¿Cómo se dice 'isla' en inglés?", "island"],
["¿Cómo se dice 'lago' en inglés?", "lake"],
["¿Cómo se dice 'río' en inglés?", "river"],
["¿Cómo se dice 'bosque' en inglés?", "forest"],
["¿Cómo se dice 'playa' en inglés?", "beach"],
["¿Cómo se dice 'hotel' en inglés?", "hotel"],
["¿Cómo se dice 'restaurante' en inglés?", "restaurant"],
["¿Cómo se dice 'escuela' en inglés?", "school"],
["¿Cómo se dice 'hospital' en inglés?", "hospital"],
["¿Cómo se dice 'tienda' en inglés?", "shop"],
["¿Cómo se dice 'mercado' en inglés?", "market"],
["¿Cómo se dice 'coche' en inglés?", "car"],
["¿Cómo se dice 'bicicleta' en inglés?", "bicycle"],
["¿Cómo se dice 'tren' en inglés?", "train"],
["¿Cómo se dice 'avión' en inglés?", "plane"],
["¿Cómo se dice 'barco' en inglés?", "boat"],
["¿Cómo se dice 'autobús' en inglés?", "bus"],
["¿Cómo se dice 'calor' en inglés?", "heat"],
["¿Cómo se dice 'frío' en inglés?", "cold"],
["¿Cómo se dice 'lluvia' en inglés?", "rain"],
["¿Cómo se dice 'nieve' en inglés?", "snow"],
["¿Cómo se dice 'viento' en inglés?", "wind"],
["¿Cómo se dice 'tormenta' en inglés?", "storm"],
["¿Cómo se dice 'estrella' en inglés?", "star"],
["¿Cómo se dice 'planeta' en inglés?", "planet"],
["¿Cómo se dice 'universo' en inglés?", "universe"],
["¿Cómo se dice 'luz' en inglés?", "light"],
["¿Cómo se dice 'sombra' en inglés?", "shadow"],
["¿Cómo se dice 'fuego' en inglés?", "fire"],
["¿Cómo se dice 'humo' en inglés?", "smoke"],
["¿Cómo se dice 'arena' en inglés?", "sand"],
["¿Cómo se dice 'roca' en inglés?", "rock"],
["¿Cómo se dice 'tierra' en inglés?", "earth"],
["¿Cómo se dice 'agua dulce' en inglés?", "freshwater"],
["¿Cómo se dice 'agua salada' en inglés?", "saltwater"],
["¿Cómo se dice 'nube' en inglés?", "cloud"],
["¿Cómo se dice 'lluvia ligera' en inglés?", "drizzle"],
["¿Cómo se dice 'granizo' en inglés?", "hail"],
["¿Cómo se dice 'trueno' en inglés?", "thunder"],
["¿Cómo se dice 'relámpago' en inglés?", "lightning"],
["¿Cómo se dice 'tormenta de nieve' en inglés?", "blizzard"],
["¿Cómo se dice 'tempestad' en inglés?", "tempest"],
["¿Cómo se dice 'cielo nocturno' en inglés?", "night sky"],
["¿Cómo se dice 'amanecer' en inglés?", "sunrise"],
["¿Cómo se dice 'atardecer' en inglés?", "sunset"],
["¿Cómo se dice 'lago congelado' en inglés?", "frozen lake"],
["¿Cómo se dice 'bosque tropical' en inglés?", "rainforest"],
["¿Cómo se dice 'desierto' en inglés?", "desert"],
["¿Cómo se dice 'jungla' en inglés?", "jungle"],
["¿Cómo se dice 'cascada' en inglés?", "waterfall"],
["¿Cómo se dice 'cueva' en inglés?", "cave"],
["¿Cómo se dice 'volcán' en inglés?", "volcano"],
["¿Cómo se dice 'glaciar' en inglés?", "glacier"],
["¿Cómo se dice 'isla desierta' en inglés?", "deserted island"],
["¿Cómo se dice 'barranco' en inglés?", "cliff"],
["¿Cómo se dice 'océano' en inglés?", "ocean"],
["¿Cómo se dice 'bahía' en inglés?", "bay"],
["¿Cómo se dice 'golfo' en inglés?", "gulf"],
["¿Cómo se dice 'estrecho' en inglés?", "strait"],
["¿Cómo se dice 'puerto' en inglés?", "port"],
["¿Cómo se dice 'playa rocosa' en inglés?", "rocky beach"],
["¿Cómo se dice 'pradera' en inglés?", "meadow"],
["¿Cómo se dice 'colina' en inglés?", "hill"],
["¿Cómo se dice 'valle' en inglés?", "valley"],
["¿Cómo se dice 'cima' en inglés?", "peak"],
["¿Cómo se dice 'acantilado' en inglés?", "cliff"],
["¿Cómo se dice 'isla volcánica' en inglés?", "volcanic island"],
["¿Cómo se dice 'lago salado' en inglés?", "salt lake"],
["¿Cómo se dice 'pantano' en inglés?", "swamp"],
["¿Cómo se dice 'marisma' en inglés?", "marsh"],
["¿Cómo se dice 'bosque de coníferas' en inglés?", "coniferous forest"],
["¿Cómo se dice 'bosque caducifolio' en inglés?", "deciduous forest"],
["¿Cómo se dice 'campo de flores' en inglés?", "flower field"],
["¿Cómo se dice 'cañón' en inglés?", "canyon"],
["¿Cómo se dice 'reloj' en inglés?", "clock"],
["¿Cómo se dice 'teléfono' en inglés?", "phone"],
["¿Cómo se dice 'computadora' en inglés?", "computer"],
["¿Cómo se dice 'teclado' en inglés?", "keyboard"],
["¿Cómo se dice 'pantalla' en inglés?", "screen"],
["¿Cómo se dice 'ratón de computadora' en inglés?", "mouse"],
["¿Cómo se dice 'impresora' en inglés?", "printer"],
["¿Cómo se dice 'libreta' en inglés?", "notebook"],
["¿Cómo se dice 'bolígrafo' en inglés?", "pen"],
["¿Cómo se dice 'lápiz' en inglés?", "pencil"],
["¿Cómo se dice 'borrador' en inglés?", "eraser"],
["¿Cómo se dice 'carpeta' en inglés?", "folder"],
["¿Cómo se dice 'mesa de oficina' en inglés?", "desk"],
["¿Cómo se dice 'silla de oficina' en inglés?", "office chair"],
["¿Cómo se dice 'ventilador' en inglés?", "fan"],
["¿Cómo se dice 'lámpara' en inglés?", "lamp"],
["¿Cómo se dice 'cama' en inglés?", "bed"],
["¿Cómo se dice 'almohada' en inglés?", "pillow"],
["¿Cómo se dice 'sábana' en inglés?", "sheet"],
["¿Cómo se dice 'manta' en inglés?", "blanket"],
["¿Cómo se dice 'cortina' en inglés?", "curtain"],
["¿Cómo se dice 'puerta principal' en inglés?", "front door"],
["¿Cómo se dice 'ventana de cocina' en inglés?", "kitchen window"],
["¿Cómo se dice 'espejo' en inglés?", "mirror"],
["¿Cómo se dice 'refrigerador' en inglés?", "refrigerator"],
["¿Cómo se dice 'estufa' en inglés?", "stove"],
["¿Cómo se dice 'horno' en inglés?", "oven"],
["¿Cómo se dice 'lavaplatos' en inglés?", "dishwasher"],
["¿Cómo se dice 'fregadero' en inglés?", "sink"],
["¿Cómo se dice 'cafetera' en inglés?", "coffee maker"],
["¿Cómo se dice 'taza' en inglés?", "cup"],
["¿Cómo se dice 'plato' en inglés?", "plate"],
["¿Cómo se dice 'cuchara' en inglés?", "spoon"],
["¿Cómo se dice 'tenedor' en inglés?", "fork"],
["¿Cómo se dice 'cuchillo' en inglés?", "knife"],
["¿Cómo se dice 'vaso' en inglés?", "glass"],
["¿Cómo se dice 'botella' en inglés?", "bottle"],
["¿Cómo se dice 'panera' en inglés?", "bread basket"],
["¿Cómo se dice 'frigorífico' en inglés?", "fridge"],
["¿Cómo se dice 'microondas' en inglés?", "microwave"],
["¿Cómo se dice 'lavadora' en inglés?", "washing machine"],
["¿Cómo se dice 'secadora' en inglés?", "dryer"],
["¿Cómo se dice 'planta de interior' en inglés?", "indoor plant"],
["¿Cómo se dice 'cuadro' en inglés?", "painting"],
["¿Cómo se dice 'estantería' en inglés?", "shelf"],
["¿Cómo se dice 'alfombra' en inglés?", "carpet"],
["¿Cómo se dice 'suelo de madera' en inglés?", "wooden floor"],
["¿Cómo se dice 'techo' en inglés?", "ceiling"],
["¿Cómo se dice 'pared' en inglés?", "wall"],
["¿Cómo se dice 'ventana grande' en inglés?", "large window"],
["¿Cómo se dice 'puerta trasera' en inglés?", "back door"]
["¿Cómo se dice 'correr' en inglés?", "run"],
["¿Cómo se dice 'caminar' en inglés?", "walk"],
["¿Cómo se dice 'saltar' en inglés?", "jump"],
["¿Cómo se dice 'nadar' en inglés?", "swim"],
["¿Cómo se dice 'volar' en inglés?", "fly"],
["¿Cómo se dice 'leer' en inglés?", "read"],
["¿Cómo se dice 'escribir' en inglés?", "write"],
["¿Cómo se dice 'dibujar' en inglés?", "draw"],
["¿Cómo se dice 'cocinar' en inglés?", "cook"],
["¿Cómo se dice 'beber' en inglés?", "drink"],
["¿Cómo se dice 'comer' en inglés?", "eat"],
["¿Cómo se dice 'dormir' en inglés?", "sleep"],
["¿Cómo se dice 'despertar' en inglés?", "wake up"],
["¿Cómo se dice 'lavar' en inglés?", "wash"],
["¿Cómo se dice 'limpiar' en inglés?", "clean"],
["¿Cómo se dice 'abrir' en inglés?", "open"],
["¿Cómo se dice 'cerrar' en inglés?", "close"],
["¿Cómo se dice 'sentarse' en inglés?", "sit"],
["¿Cómo se dice 'pararse' en inglés?", "stand"],
["¿Cómo se dice 'hablar' en inglés?", "talk"],
["¿Cómo se dice 'escuchar' en inglés?", "listen"],
["¿Cómo se dice 'mirar' en inglés?", "look"],
["¿Cómo se dice 'ver' en inglés?", "see"],
["¿Cómo se dice 'tocar' en inglés?", "touch"],
["¿Cómo se dice 'sentir' en inglés?", "feel"],
["¿Cómo se dice 'esperar' en inglés?", "wait"],
["¿Cómo se dice 'coger' en inglés?", "take"],
["¿Cómo se dice 'dar' en inglés?", "give"],
["¿Cómo se dice 'comprar' en inglés?", "buy"],
["¿Cómo se dice 'vender' en inglés?", "sell"],
["¿Cómo se dice 'enviar' en inglés?", "send"],
["¿Cómo se dice 'recibir' en inglés?", "receive"],
["¿Cómo se dice 'conducir' en inglés?", "drive"],
["¿Cómo se dice 'viajar' en inglés?", "travel"],
["¿Cómo se dice 'llegar' en inglés?", "arrive"],
["¿Cómo se dice 'salir' en inglés?", "leave"],
["¿Cómo se dice 'entrar' en inglés?", "enter"],
["¿Cómo se dice 'preguntar' en inglés?", "ask"],
["¿Cómo se dice 'responder' en inglés?", "answer"],
["¿Cómo se dice 'trabajar' en inglés?", "work"],
["¿Cómo se dice 'jugar' en inglés?", "play"],
["¿Cómo se dice 'cantar' en inglés?", "sing"],
["¿Cómo se dice 'bailar' en inglés?", "dance"],
["¿Cómo se dice 'reír' en inglés?", "laugh"],
["¿Cómo se dice 'llorar' en inglés?", "cry"],
["¿Cómo se dice 'ganar' en inglés?", "win"],
["¿Cómo se dice 'perder' en inglés?", "lose"],
["¿Cómo se dice 'empezar' en inglés?", "start"],
["¿Cómo se dice 'terminar' en inglés?", "finish"],
["¿Cómo se dice 'buscar' en inglés?", "search"],
["¿Cómo se dice 'encontrar' en inglés?", "find"],
["¿Cómo se dice 'romper' en inglés?", "break"],
["¿Cómo se dice 'arreglar' en inglés?", "fix"],
["¿Cómo se dice 'cambiar' en inglés?", "change"],
["¿Cómo se dice 'usar' en inglés?", "use"],
["¿Cómo se dice 'ayudar' en inglés?", "help"],
["¿Cómo se dice 'comprender' en inglés?", "understand"],
["¿Cómo se dice 'aprender' en inglés?", "learn"],
["¿Cómo se dice 'enseñar' en inglés?", "teach"],
["¿Cómo se dice 'recordar' en inglés?", "remember"],
["¿Cómo se dice 'olvidar' en inglés?", "forget"],
["¿Cómo se dice 'abrir la puerta' en inglés?", "open the door"],
["¿Cómo se dice 'cerrar la ventana' en inglés?", "close the window"],
["¿Cómo se dice 'encender la luz' en inglés?", "turn on the light"],
["¿Cómo se dice 'apagar la luz' en inglés?", "turn off the light"],
["¿Cómo se dice 'subir' en inglés?", "go up"],
["¿Cómo se dice 'bajar' en inglés?", "go down"],
["¿Cómo se dice 'entrar en la habitación' en inglés?", "enter the room"],
["¿Cómo se dice 'salir de la casa' en inglés?", "leave the house"],
["¿Cómo se dice 'abrir el libro' en inglés?", "open the book"],
["¿Cómo se dice 'cerrar el libro' en inglés?", "close the book"],
["¿Cómo se dice 'beber agua' en inglés?", "drink water"],
["¿Cómo se dice 'comer pan' en inglés?", "eat bread"],
["¿Cómo se dice 'lavar las manos' en inglés?", "wash hands"],
["¿Cómo se dice 'mirar la televisión' en inglés?", "watch TV"],
["¿Cómo se dice 'escuchar música' en inglés?", "listen to music"],
["¿Cómo se dice 'leer un libro' en inglés?", "read a book"],
["¿Cómo se dice 'jugar al fútbol' en inglés?", "play football"],
["¿Cómo se dice 'bailar salsa' en inglés?", "dance salsa"],
["¿Cómo se dice 'correr rápido' en inglés?", "run fast"],
["¿Cómo se dice 'caminar despacio' en inglés?", "walk slowly"],
["¿Cómo se dice 'escribir una carta' en inglés?", "write a letter"],
["¿Cómo se dice 'dibujar un dibujo' en inglés?", "draw a picture"],
["¿Cómo se dice 'cantar una canción' en inglés?", "sing a song"],
["¿Cómo se dice 'reír mucho' en inglés?", "laugh a lot"],
["¿Cómo se dice 'llorar un poco' en inglés?", "cry a little"],
["¿Cómo se dice 'ganar el juego' en inglés?", "win the game"],
["¿Cómo se dice 'perder el partido' en inglés?", "lose the match"],
["¿Cómo se dice 'empezar la clase' en inglés?", "start the class"],
["¿Cómo se dice 'terminar la tarea' en inglés?", "finish the homework"],
["¿Cómo se dice 'buscar el libro' en inglés?", "search for the book"],
["¿Cómo se dice 'encontrar la llave' en inglés?", "find the key"],
["¿Cómo se dice 'romper el juguete' en inglés?", "break the toy"],
["¿Cómo se dice 'arreglar la bicicleta' en inglés?", "fix the bicycle"],
["¿Cómo se dice 'cambiar de ropa' en inglés?", "change clothes"],
["¿Cómo se dice 'usar la computadora' en inglés?", "use the computer"],
["¿Cómo se dice 'ayudar a un amigo' en inglés?", "help a friend"]
["¿Cómo se dice 'sentir frío' en inglés?", "feel cold"],
["¿Cómo se dice 'sentir calor' en inglés?", "feel hot"],
["¿Cómo se dice 'estar feliz' en inglés?", "be happy"],
["¿Cómo se dice 'estar triste' en inglés?", "be sad"],
["¿Cómo se dice 'estar cansado' en inglés?", "be tired"],
["¿Cómo se dice 'estar enfermo' en inglés?", "be sick"],
["¿Cómo se dice 'sonreír' en inglés?", "smile"],
["¿Cómo se dice 'reírse a carcajadas' en inglés?", "laugh out loud"],
["¿Cómo se dice 'suspirar' en inglés?", "sigh"],
["¿Cómo se dice 'gritar' en inglés?", "shout"],
["¿Cómo se dice 'susurrar' en inglés?", "whisper"],
["¿Cómo se dice 'llamar por teléfono' en inglés?", "make a call"],
["¿Cómo se dice 'enviar un mensaje' en inglés?", "send a message"],
["¿Cómo se dice 'recibir un mensaje' en inglés?", "receive a message"],
["¿Cómo se dice 'escribir un correo' en inglés?", "write an email"],
["¿Cómo se dice 'leer un correo' en inglés?", "read an email"],
["¿Cómo se dice 'abrir la puerta' en inglés?", "open the door"],
["¿Cómo se dice 'cerrar la ventana' en inglés?", "close the window"],
["¿Cómo se dice 'encender la luz' en inglés?", "turn on the light"],
["¿Cómo se dice 'apagar la luz' en inglés?", "turn off the light"],
["¿Cómo se dice 'subir la escalera' en inglés?", "go up the stairs"],
["¿Cómo se dice 'bajar la escalera' en inglés?", "go down the stairs"],
["¿Cómo se dice 'sentarse en la silla' en inglés?", "sit on the chair"],
["¿Cómo se dice 'levantarse de la silla' en inglés?", "stand up from the chair"],
["¿Cómo se dice 'tomar un café' en inglés?", "have a coffee"],
["¿Cómo se dice 'tomar un té' en inglés?", "have a tea"],
["¿Cómo se dice 'comer una manzana' en inglés?", "eat an apple"],
["¿Cómo se dice 'beber jugo' en inglés?", "drink juice"],
["¿Cómo se dice 'leer un periódico' en inglés?", "read a newspaper"],
["¿Cómo se dice 'escuchar la radio' en inglés?", "listen to the radio"],
["¿Cómo se dice 'ver la televisión' en inglés?", "watch TV"],
["¿Cómo se dice 'limpiar la casa' en inglés?", "clean the house"],
["¿Cómo se dice 'lavar los platos' en inglés?", "wash the dishes"],
["¿Cómo se dice 'hacer la cama' en inglés?", "make the bed"],
["¿Cómo se dice 'planchar la ropa' en inglés?", "iron the clothes"],
["¿Cómo se dice 'cortar el césped' en inglés?", "cut the grass"],
["¿Cómo se dice 'regar las plantas' en inglés?", "water the plants"],
["¿Cómo se dice 'sacar la basura' en inglés?", "take out the trash"],
["¿Cómo se dice 'hacer ejercicio' en inglés?", "exercise"],
["¿Cómo se dice 'correr en el parque' en inglés?", "run in the park"],
["¿Cómo se dice 'nadar en la piscina' en inglés?", "swim in the pool"],
["¿Cómo se dice 'andar en bicicleta' en inglés?", "ride a bike"],
["¿Cómo se dice 'escalar la montaña' en inglés?", "climb the mountain"],
["¿Cómo se dice 'viajar en avión' en inglés?", "travel by plane"],
["¿Cómo se dice 'viajar en tren' en inglés?", "travel by train"],
["¿Cómo se dice 'viajar en barco' en inglés?", "travel by boat"],
["¿Cómo se dice 'conducir un coche' en inglés?", "drive a car"],
["¿Cómo se dice 'tomar un taxi' en inglés?", "take a taxi"],
["¿Cómo se dice 'esperar el autobús' en inglés?", "wait for the bus"],
["¿Cómo se dice 'caminar por la ciudad' en inglés?", "walk around the city"],
["¿Cómo se dice 'visitar un museo' en inglés?", "visit a museum"],
["¿Cómo se dice 'ir al cine' en inglés?", "go to the cinema"],
["¿Cómo se dice 'ver una película' en inglés?", "watch a movie"],
["¿Cómo se dice 'ir de compras' en inglés?", "go shopping"],
["¿Cómo se dice 'comprar ropa' en inglés?", "buy clothes"],
["¿Cómo se dice 'pagar en efectivo' en inglés?", "pay in cash"],
["¿Cómo se dice 'pagar con tarjeta' en inglés?", "pay with card"],
["¿Cómo se dice 'leer un libro' en inglés?", "read a book"],
["¿Cómo se dice 'escribir una carta' en inglés?", "write a letter"],
["¿Cómo se dice 'tomar fotos' en inglés?", "take photos"],
["¿Cómo se dice 'grabar un video' en inglés?", "record a video"],
["¿Cómo se dice 'usar la computadora' en inglés?", "use the computer"],
["¿Cómo se dice 'abrir un archivo' en inglés?", "open a file"],
["¿Cómo se dice 'cerrar un archivo' en inglés?", "close a file"],
["¿Cómo se dice 'imprimir un documento' en inglés?", "print a document"],
["¿Cómo se dice 'enviar un documento' en inglés?", "send a document"],
["¿Cómo se dice 'recibir un paquete' en inglés?", "receive a package"],
["¿Cómo se dice 'enviar un paquete' en inglés?", "send a package"],
["¿Cómo se dice 'llamar a un amigo' en inglés?", "call a friend"],
["¿Cómo se dice 'responder el teléfono' en inglés?", "answer the phone"],
["¿Cómo se dice 'apagar el ordenador' en inglés?", "turn off the computer"],
["¿Cómo se dice 'encender el ordenador' en inglés?", "turn on the computer"],
["¿Cómo se dice 'guardar un archivo' en inglés?", "save a file"],
["¿Cómo se dice 'borrar un archivo' en inglés?", "delete a file"],
["¿Cómo se dice 'buscar información' en inglés?", "search for information"],
["¿Cómo se dice 'encontrar información' en inglés?", "find information"],
["¿Cómo se dice 'ayudar a alguien' en inglés?", "help someone"],
["¿Cómo se dice 'pedir ayuda' en inglés?", "ask for help"],
["¿Cómo se dice 'responder preguntas' en inglés?", "answer questions"],
["¿Cómo se dice 'hacer preguntas' en inglés?", "ask questions"],
["¿Cómo se dice 'enseñar inglés' en inglés?", "teach English"],
["¿Cómo se dice 'aprender inglés' en inglés?", "learn English"],
["¿Cómo se dice 'practicar inglés' en inglés?", "practice English"],
["¿Cómo se dice 'jugar videojuegos' en inglés?", "play video games"],
["¿Cómo se dice 'escuchar música' en inglés?", "listen to music"],
["¿Cómo se dice 'ver la serie' en inglés?", "watch the series"],
["¿Cómo se dice 'leer el periódico' en inglés?", "read the newspaper"],
["¿Cómo se dice 'cocinar la cena' en inglés?", "cook dinner"],
["¿Cómo se dice 'preparar el desayuno' en inglés?", "prepare breakfast"],
["¿Cómo se dice 'lavar la ropa' en inglés?", "wash clothes"],
["¿Cómo se dice 'secar la ropa' en inglés?", "dry clothes"],
["¿Cómo se dice 'colgar la ropa' en inglés?", "hang clothes"],
["¿Cómo se dice 'planchar la camisa' en inglés?", "iron the shirt"],
["¿Cómo se dice 'limpiar el baño' en inglés?", "clean the bathroom"],
["¿Cómo se dice 'hacer la compra' en inglés?", "do the shopping"],
["¿Cómo se dice 'pagar las cuentas' en inglés?", "pay the bills"],
["¿Cómo se dice 'ir al banco' en inglés?", "go to the bank"],
["¿Cómo se dice 'enviar dinero' en inglés?", "send money"],
["¿Cómo se dice 'recibir dinero' en inglés?", "receive money"],
["¿Cómo se dice 'usar el transporte público' en inglés?", "use public transport"],
["¿Cómo se dice 'tomar el metro' en inglés?", "take the subway"],
["¿Cómo se dice 'tomar el autobús' en inglés?", "take the bus"],
["¿Cómo se dice 'andar en bicicleta' en inglés?", "ride a bike"],
["¿Cómo se dice 'correr en el parque' en inglés?", "run in the park"],
["¿Cómo se dice 'caminar con el perro' en inglés?", "walk the dog"],
["¿Cómo se dice 'abrir la puerta principal' en inglés?", "open the main door"],
["¿Cómo se dice 'cerrar la puerta trasera' en inglés?", "close the back door"],
["¿Cómo se dice 'subir las escaleras' en inglés?", "go up the stairs"],
["¿Cómo se dice 'bajar las escaleras' en inglés?", "go down the stairs"],
["¿Cómo se dice 'sentarse en el sofá' en inglés?", "sit on the sofa"],
["¿Cómo se dice 'levantarse del sofá' en inglés?", "stand up from the sofa"],
["¿Cómo se dice 'poner la mesa' en inglés?", "set the table"],
["¿Cómo se dice 'quitar la mesa' en inglés?", "clear the table"],
["¿Cómo se dice 'abrir la nevera' en inglés?", "open the fridge"],
["¿Cómo se dice 'cerrar la nevera' en inglés?", "close the fridge"],
["¿Cómo se dice 'encender el horno' en inglés?", "turn on the oven"],
["¿Cómo se dice 'apagar el horno' en inglés?", "turn off the oven"],
["¿Cómo se dice 'poner la ropa en la lavadora' en inglés?", "put clothes in the washing machine"],
["¿Cómo se dice 'sacar la ropa de la lavadora' en inglés?", "take clothes out of the washing machine"],
["¿Cómo se dice 'planchar la ropa' en inglés?", "iron the clothes"],
["¿Cómo se dice 'hacer la cama' en inglés?", "make the bed"],
["¿Cómo se dice 'cambiar la sábana' en inglés?", "change the sheet"],
["¿Cómo se dice 'regar las plantas' en inglés?", "water the plants"],
["¿Cómo se dice 'cortar las plantas' en inglés?", "trim the plants"],
["¿Cómo se dice 'sacar la basura' en inglés?", "take out the trash"],
["¿Cómo se dice 'limpiar el suelo' en inglés?", "clean the floor"],
["¿Cómo se dice 'barrer el suelo' en inglés?", "sweep the floor"],
["¿Cómo se dice 'trapear el suelo' en inglés?", "mop the floor"],
["¿Cómo se dice 'lavar las ventanas' en inglés?", "wash the windows"],
["¿Cómo se dice 'quitar el polvo' en inglés?", "dust the furniture"],
["¿Cómo se dice 'abrir la ventana' en inglés?", "open the window"],
["¿Cómo se dice 'cerrar la ventana' en inglés?", "close the window"],
["¿Cómo se dice 'encender la luz del salón' en inglés?", "turn on the living room light"],
["¿Cómo se dice 'apagar la luz del salón' en inglés?", "turn off the living room light"],
["¿Cómo se dice 'subir el volumen de la televisión' en inglés?", "turn up the TV volume"],
["¿Cómo se dice 'bajar el volumen de la televisión' en inglés?", "turn down the TV volume"],
["¿Cómo se dice 'poner música' en inglés?", "play music"],
["¿Cómo se dice 'parar la música' en inglés?", "stop the music"],
["¿Cómo se dice 'reproducir un video' en inglés?", "play a video"],
["¿Cómo se dice 'pausar un video' en inglés?", "pause a video"],
["¿Cómo se dice 'guardar un archivo' en inglés?", "save a file"],
["¿Cómo se dice 'borrar un archivo' en inglés?", "delete a file"],
["¿Cómo se dice 'descargar un archivo' en inglés?", "download a file"],
["¿Cómo se dice 'subir un archivo' en inglés?", "upload a file"],
["¿Cómo se dice 'enviar un correo electrónico' en inglés?", "send an email"],
["¿Cómo se dice 'recibir un correo electrónico' en inglés?", "receive an email"],
["¿Cómo se dice 'imprimir un documento' en inglés?", "print a document"],
["¿Cómo se dice 'escuchar un podcast' en inglés?", "listen to a podcast"],
["¿Cómo se dice 'ver un programa de televisión' en inglés?", "watch a TV show"],
["¿Cómo se dice 'leer un artículo' en inglés?", "read an article"],
["¿Cómo se dice 'tomar notas' en inglés?", "take notes"],
["¿Cómo se dice 'apuntar algo' en inglés?", "write something down"],
["¿Cómo se dice 'dibujar un plano' en inglés?", "draw a plan"],
["¿Cómo se dice 'hacer un esquema' en inglés?", "make a diagram"],
["¿Cómo se dice 'buscar información en Internet' en inglés?", "search for information online"],
["¿Cómo se dice 'encontrar información en Internet' en inglés?", "find information online"],
["¿Cómo se dice 'usar el teléfono móvil' en inglés?", "use the mobile phone"],
["¿Cómo se dice 'llamar a alguien' en inglés?", "call someone"],
["¿Cómo se dice 'responder la llamada' en inglés?", "answer the call"],
["¿Cómo se dice 'colgar el teléfono' en inglés?", "hang up the phone"],
["¿Cómo se dice 'mandar un mensaje de texto' en inglés?", "send a text message"],
["¿Cómo se dice 'recibir un mensaje de texto' en inglés?", "receive a text message"],
["¿Cómo se dice 'apagar el móvil' en inglés?", "turn off the phone"],
["¿Cómo se dice 'encender el móvil' en inglés?", "turn on the phone"],
["¿Cómo se dice 'tomar una foto' en inglés?", "take a photo"],
["¿Cómo se dice 'grabar un video' en inglés?", "record a video"],
["¿Cómo se dice 'subir una foto a redes sociales' en inglés?", "upload a photo to social media"],
["¿Cómo se dice 'comentar en redes sociales' en inglés?", "comment on social media"],
["¿Cómo se dice 'dar like en redes sociales' en inglés?", "like on social media"],
["¿Cómo se dice 'compartir en redes sociales' en inglés?", "share on social media"],
["¿Cómo se dice 'leer un mensaje' en inglés?", "read a message"],
["¿Cómo se dice 'responder un mensaje' en inglés?", "reply to a message"],
["¿Cómo se dice 'cerrar sesión' en inglés?", "log out"],
["¿Cómo se dice 'iniciar sesión' en inglés?", "log in"],
["¿Cómo se dice 'buscar un contacto' en inglés?", "search for a contact"],
["¿Cómo se dice 'añadir un contacto' en inglés?", "add a contact"],
["¿Cómo se dice 'eliminar un contacto' en inglés?", "delete a contact"],
["¿Cómo se dice 'enviar un paquete' en inglés?", "send a package"],
["¿Cómo se dice 'recibir un paquete' en inglés?", "receive a package"],
["¿Cómo se dice 'reservar una cita' en inglés?", "book an appointment"],
["¿Cómo se dice 'cancelar una cita' en inglés?", "cancel an appointment"],
["¿Cómo se dice 'confirmar una cita' en inglés?", "confirm an appointment"],
["¿Cómo se dice 'llegar a tiempo' en inglés?", "arrive on time"],
["¿Cómo se dice 'llegar tarde' en inglés?", "arrive late"],
["¿Cómo se dice 'hacer una llamada de emergencia' en inglés?", "make an emergency call"],
["¿Cómo se dice 'pedir ayuda' en inglés?", "ask for help"],
["¿Cómo se dice 'ayudar a alguien' en inglés?", "help someone"],
["¿Cómo se dice 'llamar a la policía' en inglés?", "call the police"],
["¿Cómo se dice 'llamar a los bomberos' en inglés?", "call the fire department"],
["¿Cómo se dice 'llamar a un médico' en inglés?", "call a doctor"],
["¿Cómo se dice 'ir al hospital' en inglés?", "go to the hospital"],
["¿Cómo se dice 'ir a la farmacia' en inglés?", "go to the pharmacy"],
["¿Cómo se dice 'tomar medicina' en inglés?", "take medicine"],
["¿Cómo se dice 'beber agua' en inglés?", "drink water"],
["¿Cómo se dice 'comer comida saludable' en inglés?", "eat healthy food"],
["¿Cómo se dice 'hacer deporte' en inglés?", "do sports"],
["¿Cómo se dice 'correr en la pista' en inglés?", "run on the track"],
["¿Cómo se dice 'andar en bicicleta en el parque' en inglés?", "ride a bike in the park"],
["¿Cómo se dice 'nadar en la piscina' en inglés?", "swim in the pool"],
["¿Cómo se dice 'jugar fútbol' en inglés?", "play football"],
["¿Cómo se dice 'jugar baloncesto' en inglés?", "play basketball"],
["¿Cómo se dice 'jugar tenis' en inglés?", "play tennis"],
["¿Cómo se dice 'practicar yoga' en inglés?", "practice yoga"],
["¿Cómo se dice 'meditar' en inglés?", "meditate"],
["¿Cómo se dice 'relajarse' en inglés?", "relax"],
["¿Cómo se dice 'dormir temprano' en inglés?", "sleep early"],
["¿Cómo se dice 'despertarse tarde' en inglés?", "wake up late"]


];

const adivinanzaElem = document.getElementById("adivinanza");
const input = document.getElementById("input");
const boton = document.getElementById("boton");
const mensaje = document.getElementById("mensaje");
const jugarBtn = document.getElementById("jugar");
const aprenderBtn = document.getElementById("aprender");

// Crear botón “Anterior” dinámicamente
const botonAnterior = document.createElement("button");
botonAnterior.textContent = "Anterior";
botonAnterior.className = "btn btn-secondary btn-lg me-2"; // estilo bootstrap
botonAnterior.style.display = "none"; // oculto por defecto
boton.parentNode.insertBefore(botonAnterior, boton); // lo ponemos antes de “boton”

let indice = 0;
let modo = ""; // "aprender" o "jugar"

function hablar(texto) {
  const mensajeVoz = new SpeechSynthesisUtterance(texto);
  mensajeVoz.lang = "en-US"; // o "es-ES" si quieres español
  window.speechSynthesis.speak(mensajeVoz);
}


// Elegir modo
jugarBtn.addEventListener("click", () => {
  modo = "jugar";
  indice = 0;
  botonAnterior.style.display = "none"; // oculto en jugar
  mostrarPregunta();
});

aprenderBtn.addEventListener("click", () => {
  modo = "aprender";
  indice = 0;
  botonAnterior.style.display = "inline-block"; // mostrar en aprender
  mostrarPregunta();
});

// Función que se comporta según el modo
function mostrarPregunta() {
  if (indice >= preguntas.length) {
    adivinanzaElem.textContent = "¡Genial! Has aprendido todas las palabras 🏆";
    mensaje.textContent = "";
    input.style.display = "none";
    boton.style.display = "none";
    botonAnterior.style.display = modo === "aprender" ? "inline-block" : "none";
    return;
  }

  if (indice < 0) indice = 0; // evitar índice negativo

  adivinanzaElem.textContent = preguntas[indice][0];

  if (modo === "aprender") {
    mensaje.textContent = preguntas[indice][1];
    input.style.display = "none";
    boton.style.display = "inline-block";
    boton.textContent = "Next";
    botonAnterior.style.display = indice > 0 ? "inline-block" : "none";
    hablar(preguntas[indice][1]);
  } else {
    mensaje.textContent = "";
    input.style.display = "block";
    input.value = "";
    input.focus();
    boton.style.display = "inline-block";
    boton.textContent = "Responder";
    botonAnterior.style.display = "none";
  }
}

// Listener único para el botón “boton”
boton.addEventListener("click", () => {
  if (modo === "aprender") {
    indice++;
    mostrarPregunta();
  } else if (modo === "jugar") {
    const respuestaUsuario = input.value.trim().toLowerCase();
    if (respuestaUsuario === preguntas[indice][1]) {
      mensaje.textContent = "¡Correcto! 🏆";
      indice++;
      setTimeout(mostrarPregunta, 1000);
    } else {
      mensaje.textContent = "No es correcto. Intenta de nuevo.";
      input.value = "";
      input.focus();
    }
  }
});

// Listener para botón “Anterior”
botonAnterior.addEventListener("click", () => {
  if (modo === "aprender" && indice > 0) {
    indice--;
    mostrarPregunta();
  }
});
